### ISSUE TITLE
Not set up for British English

### ISSUE THREAD

**Issue by fruitbat2000** [passy/tube-trains-bot#7]
I just tried to use this on my Home and the response was 'Sorry, Tube Trains is not supported on devices set up for British English' (or something similarly useful).

Considering this api is only useful to Brits, I thought I'd point it out :)

**Comment by passy** [comment]
This is a super weird one. This *used to* work with British English - before the Google Home official had launched in the UK. On launch day, or slightly after, they *disabled* all third-party integrations for anything but US English. Why they made this choice, I have no idea, but there's currently no way to whitelist an Action to work with anything but US English.

Let's keep this issue open, because it clearly *is* an issue. I hope they'll fix this soon.

**Comment by passy** [comment]
For reference, I asked in the support community here a while ago: https://plus.google.com/+PascalHartig/posts/YU5JfPPLPTH

**Comment by fruitbat2000** [comment]
Ah ok, that IS weird but hopefully something that will get fixed in the fullness of time. Thanks for the action btw, when it works it's going to be one of my go-to morning requests for Home :)

**Comment by passy** [comment]
@fruitbat2000 That's awesome! I'm really happy to hear that. Thanks. :)

**Comment by passy** [comment]
Google has now made Actions on Google available in 207 countries. Yay. :)
